### ISSUE TITLE
Connection refused

### ISSUE THREAD

**Issue by sunnyandmorning** [chenzishuo1994/Onrobot-Hex-sensor-python-adapter#1]
Thank you for uploading, I connect the PC and the computer box of sensor with the network cable.After running the program, connection refused is displayed. What work I need to do before running the program?

**Comment by sunnyandmorning** [comment]
I solved the problem of connection failure. After running the program, he quickly ended, and there was no output

**Comment by chenzishuo1994** [comment]
Sorry to reply late, the default IP address is 192.168.1.1. You can link the address in the browser to check if the configuration of sensor is normal.  If it is correct, I think the program will output the data.

**Comment by sunnyandmorning** [comment]
Thanks  reply, I checked the IP address of 192.168.1.1 with the webpage link, and found that the force feedback data can be read in real time on the webpage, but then I run the program, there is still no output.  (Q_Q)

**Comment by sunnyandmorning** [comment]
Thanks reply, I checked the IP address of 192.168.1.1 with the webpage link, and found that the force feedback data can be read in real time on the webpage, but then I run the program, there is still no output.

**Comment by sunnyandmorning** [comment]
After reading the user manual, I found that the problem may be that web pages and UDP cannot be used at the same time.
